---
- name: Deploy Cisco AnyConnect on Windows clients
  hosts: windows_clients
  tasks:
    - name: Copy Cisco AnyConnect installer to the remote machine
      win_copy:
        src: /path/to/anyconnect-installer.exe
        dest: C:\Temp\anyconnect-installer.exe

    - name: Install Cisco AnyConnect VPN client
      win_package:
        path: C:\Temp\anyconnect-installer.exe
        product_id: "{Product-ID-from-AnyConnect}"  # Puedes buscar este ID si es necesario
        arguments: '/silent /install'
        state: present
        creates_path: 'C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\vpnui.exe'

    - name: Create Cisco AnyConnect profile directory
      win_file:
        path: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Profile'
        state: directory

    - name: Deploy VPN profile configuration
      win_copy:
        src: /path/to/anyconnect-profile.xml
        dest: 'C:\ProgramData\Cisco\Cisco AnyConnect Secure Mobility Client\Profile\vpn_profile.xml'

    - name: Ensure Cisco AnyConnect service is running
      win_service:
        name: 'vpnagent'
        state: started
        start_mode: auto

    - name: Clean up installer file
      win_file:
        path: C:\Temp\anyconnect-installer.exe
        state: absent
