---
- name: Inventario y control de software instalado usando winget
  hosts: all
  vars:
    software_permitido:
      - Google Chrome
      - Microsoft Office
      - Notepad++
      - Adobe Acrobat Reader

  tasks:
    - name: Verificar si winget está instalado
      win_shell: |
        winget --version
      register: winget_check
      failed_when: winget_check.rc != 0
      changed_when: false

    - name: Obtener lista de paquetes instalados con winget
      win_shell: |
        winget list --source winget |
        ForEach-Object { ($_ -split '\s{2,}')[0] } |
        ConvertTo-Json -Depth 1
      register: software_list

    - name: Convertir lista de software a JSON
      set_fact:
        software_instalado: "{{ software_list.stdout | from_json }}"

    - name: Filtrar software no permitido
      set_fact:
        software_no_permitido: >-
          {{ software_instalado | difference(software_permitido) | list }}

    - name: Mostrar alerta si hay software no permitido
      debug:
        msg: "Se encontró software no permitido: {{ software_no_permitido }}"
      when: software_no_permitido | length > 0

#    - name: Desinstalar software no permitido
#      win_shell: |
#        winget uninstall "{{ item }}" --silent
#      with_items: "{{ software_no_permitido }}"
#      when: software_no_permitido | length > 0
