---
- name: Validacion de los pre-requisitos para la creacion de una maquina
  hosts: all
  gather_facts: false
  tasks:
    - name: Validacion
      ansible.builtin.debug:
        msg: Los recursos necesarios para la creacion de la maquina existen
