---
- hosts: localhost
  vars_files: smtp_secrets.yml
  vars:
    - elemento: host01-sharon
    - subred: 192.168.0.0/24
    - EVI: 2398

  tasks:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: "{{ email_smtp_username }}"
        password: "{{ email_smtp_password }}"
        to: jmanuelcalvo@gmail.com
        subject: Script de configuracion para {{ elemento }} y {{ subred }}
        body: "{{ lookup('template','templates/mail_body.html.j2') }}"
        attach:
          - files/script.txt
        subtype: html
        charset: utf8
