---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-critica
  namespace: demo-autocura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:latest
