---
- name: Validar conectividad de red a OCP
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Verificar si el puerto 6443 está escuchando
      ansible.builtin.wait_for:
        host: api.rm2.thpm.p1.openshiftapps.com
        port: 6443
        timeout: 10
        msg: "No hay conectividad al puerto 6443 de OpenShift"

    - name: Confirmar éxito
      ansible.builtin.debug:
        msg: "¡Conectividad de red confirmada!"
