- name: OpenShift Per-Namespace Report
  hosts: openshift_namespaces
  gather_facts: false
  connection: local

  vars:
    ocp_namespace: "{{ inventory_hostname }}"

  tasks:

    - name: Get Pods
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ ocp_namespace }}"
      register: pods_info

    - name: Get Deployments
      kubernetes.core.k8s_info:
        kind: Deployment
        namespace: "{{ ocp_namespace }}"
      register: deployments_info

    - name: Get Services
      kubernetes.core.k8s_info:
        kind: Service
        namespace: "{{ ocp_namespace }}"
      register: services_info
