---
- name: Aprovisionar Entorno de Demo en OpenShift
  hosts: localhost
  connection: local
  tasks:
    - name: Crear Namespace para la Demo
      redhat.openshift.k8s: # Cambiado de kubernetes.core a redhat.openshift
        api_key: "{{ query('ansible.builtin.env', 'K8S_AUTH_API_KEY') | default(omit) }}"
        host: "{{ query('ansible.builtin.env', 'K8S_AUTH_HOST') | default(omit) }}"
        verify_ssl: false # Útil si usas certificados auto-firmados en la demo
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: demo-autocura
        state: present

    - name: Desplegar Aplicación Web Crítica
      redhat.openshift.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: web-critica
            namespace: demo-autocura
          spec:
            replicas: 3
            selector:
              matchLabels:
                app: web
            template:
              metadata:
                labels:
                  app: web
              spec:
                containers:
                - name: nginx
                  image: nginxinc/nginx-unprivileged:latest
