---
- name: Generar Reporte de AWS
  hosts: all
  become: true              
  gather_facts: true        
  tasks:
    - name: Ejecutar el rol de reporte de AWS de Shadowman
      ansible.builtin.include_role:
        name: shadowman.reports.build_report_aws
