---
- name: KVM Dynamic Inventory Discovery
  hosts: up.jmanuelcalvo.com
  gather_facts: false

  vars:
    inventory_output: "/tmp/kvm_inventory.yml"

  tasks:

    - name: Obtener listado de VMs
      command: virsh list --all --name
      register: vm_list

    - name: Limpiar listado
      set_fact:
        vm_names: "{{ vm_list.stdout_lines | reject('equalto', '') | list }}"

    - name: Mostrar VMs encontradas
      debug:
        var: vm_names

    - name: Obtener informacion de interfaces
      command: "virsh domifaddr {{ item }}"
      loop: "{{ vm_names }}"
      register: vm_ips
      ignore_errors: true

    - name: Construir estructura de inventario
      set_fact:
        dynamic_inventory: "{{ dynamic_inventory | default({}) | combine(new_entry, recursive=True) }}"
      vars:
        ip_found: >-
          {{
            (
              item.stdout_lines |
              select('search', 'ipv4') |
              list |
              first |
              default('')
            ).split()[3].split('/')[0]
            if (
              item.stdout_lines |
              select('search', 'ipv4') |
              list |
              length > 0
            )
            else 'NO_IP'
          }}

        vm_name: "{{ item.item }}"

        new_entry:
          all:
            hosts:
              "{{ vm_name }}":
                ansible_host: "{{ ip_found }}"
                kvm_host: "{{ inventory_hostname }}"
      loop: "{{ vm_ips.results }}"

    - name: Mostrar inventario generado
      debug:
        var: dynamic_inventory

    - name: Guardar inventario YAML
      copy:
        content: "{{ dynamic_inventory | to_nice_yaml }}"
        dest: "{{ inventory_output }}"
