---
- name: Register RHEL 8 system with Red Hat
  hosts: all
  become: true
  gather_facts: true
  tasks:

    - name: Ensure subscription-manager package is installed
      ansible.builtin.package:
        name: subscription-manager
        state: present

    - name: Check if system is already registered
      ansible.builtin.stat:
        path: /etc/pki/consumer/cert.pem
      register: rhsm_cert

    - name: Register system using Red Hat credentials
      community.general.redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        auto_attach: "{{ rhsm_auto_attach | default(true) }}"
      when: not rhsm_cert.stat.exists
      no_log: true

    - name: Display subscription status
      ansible.builtin.command:
        cmd: subscription-manager status
      register: subscription_status
      changed_when: false

    - name: Show subscription status
      ansible.builtin.debug:
        var: subscription_status.stdout
