---
- name: Obtener información de máquinas virtuales en VMware
  hosts: localhost
  gather_facts: no
  vars:
    vm_folder: "/SDDC-Datacenter/vm/Workloads/sandbox-2jbkj"
  
  tasks:
    - name: Obtener lista de máquinas virtuales y sus estados
      community.vmware.vmware_vm_info:
        folder: "{{ vm_folder }}"
      register: vm_info

    - name: Mostrar información de las máquinas virtuales
      debug:
        var: vm_info.virtual_machines
