---
- hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: Set the state of a virtual machine to poweroff on off
      community.vmware.vmware_guest_powerstate:
        #      folder: /SDDC-Datacenter/Workloads/sandbox-9l52q
        folder: Workloads/{{ sandbox }}/
        name: "{{ nombre }}"
        state: "{{ vm_state }}" # powered-on o powered-off
      delegate_to: localhost
      register: deploy

    - name: Print the generated password
      debug:
        msg: The Output is {{ deploy }}
