---
- name: Obtener información de máquinas virtuales en VMware
  hosts: localhost
  gather_facts: false
  vars:
    vm_folder: /SDDC-Datacenter/vm/Workloads/sandbox-2jbkj

  tasks:
    - name: Obtener lista de máquinas virtuales y sus estados
      community.vmware.vmware_vm_info:
        folder: "{{ vm_folder }}"
      register: vm_info

    - name: Mostrar información de las máquinas virtuales
      debug:
        var: vm_info.virtual_machines

    - name: Formatear la salida en una tabla
      ansible.builtin.debug:
        msg: >
          {% set header = "| Nombre de VM                   | Sistema Operativo                                     | Estado          |" %}
          {% set separator = "|--------------------------------|------------------------------------------------------|-----------------|" %}
          {% set rows = [] %}
          {% for vm in vm_info.virtual_machines %}
          {% set vm_name = vm.guest_name | default('N/A') %}
          {% set os_name = vm.guest_fullname | default('N/A') %}
          {% set state = vm.power_state | default('N/A') %}
          {% set row = "| " + vm_name.ljust(30) + " | " + os_name.ljust(50) + " | " + state.ljust(15) + " |" %}
          {% set _ = rows.append(row) %}
          {% endfor %}
          {{ header }}
          {{ separator }}
          {{ rows | join('\n') }}
