---
- name: Obtener información de máquinas virtuales en VMware
  hosts: localhost
  gather_facts: no
  
  tasks:
    - name: Obtener lista de máquinas virtuales y sus estados
      community.vmware.vmware_vm_info:
      register: vm_info

    - name: Mostrar información de las máquinas virtuales
      debug:
        var: vm_info.virtual_machines
