---
- name: Webhook Demo

  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

rules:
  - name: Ver evento

    condition: event.meta is defined

    action:
      print_event:
        pretty: true
