---
- name: Webhook Demo
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Ejecutar Job
      condition: event is defined

      action:
        run_job_template:
          name: EDA Demo
          organization: Default
          extra_vars:
            ticket: "{{ event.ticket | default('') }}"
            hostname: "{{ event.hostname | default('') }}"
            action: "{{ event.action | default('') }}"
            requested_by: "{{ event.requested_by | default('') }}"
