---
- name: Escuchar webhooks
  hosts: localhost

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: Ver evento

      condition: event.meta.headers is defined
      action:
        print_event:
          pretty: true
