apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: vm-dropdown-test
  title: VM Dropdown Test
  description: Prueba de dropdown

spec:
  owner: group:default/team-platform
  type: service

  parameters:
    - title: Selección de VM

      properties:
        vm:
          title: Seleccione una VM
          type: string
          enum:
            - Bobbie Kshlerin
            - Conrad Bogan
            - Ronald Wehner
            - Hector Feest II
            - Cecilia Schuppe-Dicki
            - Stuart Watsica
