
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: vm-dynamic-survey-demo
  title: VM Dynamic Survey Demo
  description: Primera prueba de formulario para seleccionar una VM

spec:
  owner: user:default/guest
  type: service

  parameters:
    - title: Selección de máquina virtual
      required:
        - vm_id
      properties:
        vm_id:
          title: Máquina virtual
          type: string
          description: Selecciona una VM de prueba
          enum:
            - "1"
            - "2"
            - "3"
          enumNames:
            - "grey — ID 1"
            - "teal — ID 2"
            - "gold — ID 3"

  steps: []
