---
- name: Desplegar la aplicacion Pacman en un servidor Web
  gather_facts: false
  hosts: all
  tasks:

    
    - name: Red Hat selinux disable
      ansible.builtin.command: setenforce 0

    - name: Clonar el repo de pacman en la ruta del servidor Web
      ansible.builtin.git:
        repo: https://github.com/jmanuelcalvo/cordillera-app.git
        dest: /tmp/app

    - name: Copiar todo el contenido de /app a /html
      ansible.builtin.copy:
        src: /var/www/html/app/       # La barra "/" al final es clave para copiar el contenido y no la carpeta completa
        dest: /var/www/html/
        remote_src: yes                # Indica que el origen ya está dentro del servidor remoto

    - name: Eliminar la carpeta /app que ya quedó vacía (Opcional)
      ansible.builtin.file:
        path: /tmp/app
        state: absent
    
    - name: Iniciar servicio de apache
      ansible.builtin.service:
        name: httpd
        state: started   
                
