---
- name: Cambiar la contraseña de un usuario
  hosts: servidores
  become: true
  vars:
    target_user: jmanuel # Define aquí el usuario al que se le cambiará la contraseña
    new_password: NuevaContraseña123 # Define aquí la nueva contraseña

  tasks:
    - name: Verificar si el usuario existe
      ansible.builtin.getent:
        database: passwd
        key: "{{ target_user }}"
      register: user_info
      failed_when: user_info is not defined or user_info is none
      ignore_errors: false

    - name: Generar un hash de la contraseña (solo local)
      delegate_to: localhost
      ansible.builtin.command:
        cmd: openssl passwd -6 '{{ new_password }}'
      register: password_hash
      changed_when: false

    - name: Cambiar la contraseña del usuario
      ansible.builtin.user:
        name: "{{ target_user }}"
        password: "{{ password_hash.stdout }}"
      when: user_info is defined
      register: change_password_result

    - name: Mostrar mensaje de éxito
      ansible.builtin.debug:
        msg: La contraseña del usuario '{{ target_user }}' se ha cambiado correctamente.
      when: change_password_result.changed
