---
- name: Chequear y limpiar memoria RAM en Linux y registrar ejecuciones
  hosts: all
  become: yes
  vars:
    threshold: 20  # Porcentaje de uso máximo permitido (modificable)
    contador_file: /tmp/contador.txt  # Archivo para registrar el contador

  tasks:
    - name: Obtener uso de memoria
      ansible.builtin.shell: free | awk '/^Mem:/ {print $3/$2 * 100.0}'
      register: memory_usage
      changed_when: false

    - name: Mostrar uso de memoria
      ansible.builtin.debug:
        msg: "Uso actual de memoria: {{ memory_usage.stdout | float }}%"

    - name: Crear archivo de contador si no existe
      ansible.builtin.copy:
        content: "0\n"
        dest: "{{ contador_file }}"
        force: no

    - name: Limpiar caches si el uso supera el umbral
      ansible.builtin.shell: echo 3 > /proc/sys/vm/drop_caches
      when: memory_usage.stdout | float > threshold

    - name: Incrementar el contador si se ejecuta la limpieza
      ansible.builtin.shell: |
        contador=$(cat {{ contador_file }})
        echo $((contador + 1)) > {{ contador_file }}
      when: memory_usage.stdout | float > threshold

    - name: Leer archivo de contador desde el nodo remoto
      ansible.builtin.slurp:
        src: /tmp/contador.txt
      register: contador_content

    - name: Mostrar cantidad de ejecuciones
      ansible.builtin.debug:
        msg: "El comando para liberar memoria ha sido ejecutado {{ contador_content['content'] | b64decode | int }} veces."
  
