---
- name: Validate ServiceNow connectivity
  hosts: localhost
  gather_facts: false

  collections:
    - servicenow.itsm

  vars:
    snow_username: "{{ lookup('env','SN_USER') }}"

  tasks:

    - name: Get RITMs
      servicenow.itsm.api_info:
        resource: sc_req_item
        columns:
          - number
          - short_description
          - state
          - sys_id
          - opened_at
      register: ritms
  
#    - name: Query one incident
#      servicenow.itsm.api_info:
#        resource: incident
#      register: result

    - name: Show result
      ansible.builtin.debug:
        var: ritms.record
