---
- name: Get one RITM
  hosts: localhost
  gather_facts: false

  collections:
    - servicenow.itsm

  vars:
    ritm_number: "RITM0000005"

  tasks:

    - name: Search RITM
      servicenow.itsm.api_info:
        resource: sc_req_item
        sysparm_query: "number={{ ritm_number }}"
        columns:
          - number
          - sys_id
          - short_description
          - state
      register: ritm

    - name: Show RITM
      debug:
        var: ritm.record

    - name: Save sys_id
      set_fact:
        ritm_sysid: "{{ ritm.record[0].sys_id }}"

    - debug:
        msg:
          - "RITM={{ ritm.record[0].number }}"
          - "SYS_ID={{ ritm_sysid }}"
          - "STATE={{ ritm.record[0].state }}"
